"""empty message

Revision ID: 17d7455d545f
Revises: f4ab20db3806
Create Date: 2024-11-15 18:04:56.125907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d7455d545f'
down_revision = 'f4ab20db3806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_agenda', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
