"""empty message

Revision ID: 63d4611b839d
Revises: a0e7554c161e
Create Date: 2024-11-02 09:27:16.848447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d4611b839d'
down_revision = 'a0e7554c161e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('document', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meet_number', sa.Integer(), nullable=False),
    sa.Column('meet_description', sa.Text(), nullable=False),
    sa.Column('meet_regdate', sa.DateTime(), nullable=True),
    sa.Column('meet_date', sa.DateTime(), nullable=False),
    sa.Column('meet_location', sa.Text(), nullable=False),
    sa.Column('meet_type_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['meet_type_id'], ['meeting_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meetings_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.ForeignKeyConstraint(['meetings_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_minute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minute_number', sa.Integer(), nullable=True),
    sa.Column('addannotation', sa.Text(), nullable=True),
    sa.Column('aproved_date', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.Text(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_agenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agenda_topic', sa.Text(), nullable=False),
    sa.Column('agenda_protocol', sa.Text(), nullable=True),
    sa.Column('agenda_interested', sa.Text(), nullable=True),
    sa.Column('agenda_description', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('minute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['minute_id'], ['meeting_minute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_agenda')
    op.drop_table('meeting_minute')
    op.drop_table('meeting_attendees')
    op.drop_table('meetings')
    op.drop_table('meeting_type')
    op.drop_table('attendees')
    # ### end Alembic commands ###
