"""updates in institution

Revision ID: a0e7554c161e
Revises: 06ec0502ae13
Create Date: 2024-10-29 20:13:18.599762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e7554c161e'
down_revision = '06ec0502ae13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_institution_country_id_country', 'country', ['country_id'], ['id'])
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['country'], ['id'])
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
