"""empty message

Revision ID: baf4ceb4698e
Revises: bc6bcb27dc82
Create Date: 2024-11-07 22:37:48.199701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf4ceb4698e'
down_revision = 'bc6bcb27dc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.alter_column('attendee_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.alter_column('attendee_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
