"""empty message

Revision ID: c765fb0d3ab8
Revises: 32b882f6095d
Create Date: 2024-10-29 18:52:34.180664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c765fb0d3ab8'
down_revision = '32b882f6095d'
branch_labels = None
depends_on = None
'''
naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
'''

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.orm.session import Session
    from sqlalchemy.sql import text
    session = Session(bind=op.get_bind())
    session.execute(text("PRAGMA foreign_keys = ON;"))
    session.commit()
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('country', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_institution_country_id_country'), 'country', ['country_id'], ['id'])
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_institution_country_id_country', type_='foreignkey')
        batch_op.create_foreign_key('fk_institution_country_id_country', 'country', ['country'], ['id'])
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###
