"""empty message

Revision ID: f4ab20db3806
Revises: baf4ceb4698e
Create Date: 2024-11-15 16:11:36.535363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ab20db3806'
down_revision = 'baf4ceb4698e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_attendees', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
